CREATE TABLE [TA].[TravelAuthorization] (
    [TravelAuthorizationID]                 UNIQUEIDENTIFIER CONSTRAINT [DF_TravelAuthorization_TravelAuthorizationID] DEFAULT (newid()) NOT NULL,
    [TravelAuthorizationNumber]             NVARCHAR (14)    NOT NULL,
    [UserID]                                UNIQUEIDENTIFIER NULL,
    [TravelersName]                         NVARCHAR (2000)  NULL,
    [PurposeOfTravel]                       NVARCHAR (2000)  NULL,
    [TripSchemaCode]                        UNIQUEIDENTIFIER NULL,
    [ModeOfTravelCode]                      UNIQUEIDENTIFIER NULL,
    [SecurityClearance]                     BIT              NULL,
    [SecurityTraining]                      BIT              NULL,
    [StatusCode]                            NVARCHAR (3)     NULL,
    [CreatedDate]                           DATETIME         CONSTRAINT [DF_TravelAuthorization_CreatedDate] DEFAULT (getdate()) NULL,
    [CreatedBy]                             UNIQUEIDENTIFIER NULL,
    [UpdatedDate]                           DATETIME         NULL,
    [UpdatedBy]                             UNIQUEIDENTIFIER NULL,
    [isDeleted]                             BIT              CONSTRAINT [DF_TravelAuthorization_isDeleted] DEFAULT ((0)) NULL,
    [CityOfAccommodation]                   NVARCHAR (500)   NULL,
    [IsPrivateStay]                         BIT              NULL,
    [PrivateStayDates]                      NVARCHAR (500)   NULL,
    [IsPrivateDeviation]                    BIT              NULL,
    [PrivateDeviationLegs]                  NVARCHAR (500)   NULL,
    [IsAccommodationProvided]               BIT              NULL,
    [AccommodationDetails]                  NVARCHAR (500)   NULL,
    [IsTravelAdvanceRequested]              BIT              NULL,
    [TravelAdvanceCurrency]                 UNIQUEIDENTIFIER NULL,
    [TravelAdvanceAmount]                   FLOAT (53)       NULL,
    [TravelAdvanceMethod]                   NVARCHAR (50)    NULL,
    [IsVisaObtained]                        INT              NULL,
    [VisaIssued]                            NVARCHAR (500)   NULL,
    [IsVaccinationObtained]                 INT              NULL,
    [IsSecurityClearanceRequestedByMission] BIT              NULL,
    [TAConfirm]                             BIT              NULL,
    [IsTecComplete]                         BIT              NULL,
    [PrivateStayDateFrom]                   DATETIME         NULL,
    [PrivateStayDateTo]                     DATETIME         NULL,
    [FirstName]                             NVARCHAR (500)   NULL,
    [MiddleName]                            NVARCHAR (500)   NULL,
    [LastName]                              NVARCHAR (500)   NULL,
    [IsNotForDSA]                           BIT              NULL,
    [ExpenditureNotApplicable]              BIT              NULL,
    [AdvancesNotApplicable]                 BIT              NULL,
    [FamilyMembers]                         NVARCHAR (4000)  NULL,
    [DocumentNumber]                        NVARCHAR (100)   NULL,
    CONSTRAINT [PK_TravelAuthorization_1] PRIMARY KEY CLUSTERED ([TravelAuthorizationID] ASC) WITH (FILLFACTOR = 80)
);



